"""Add image_urls, description, more_info columns to books table.

Revision ID: 967c28cee86b
Revises: 08d97681839a
Create Date: 2025-12-26 09:37:49.693132

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "967c28cee86b"
down_revision = "08d97681839a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("image_urls", sa.Text(), nullable=True))
    op.add_column("books", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("books", sa.Column("more_info", sa.JSON(), nullable=True))
    op.drop_column("books", "image_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("image_url", mysql.TEXT(), nullable=True))
    op.drop_column("books", "more_info")
    op.drop_column("books", "description")
    op.drop_column("books", "image_urls")
    # ### end Alembic commands ###
