"""empty message.

Revision ID: c245b7ef033b
Revises: 93e42801cfb1
Create Date: 2026-01-09 17:42:33.579598

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "c245b7ef033b"
down_revision = "93e42801cfb1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books",
        "price",
        existing_type=mysql.FLOAT(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "order_items",
        "price_at_purchase",
        existing_type=mysql.FLOAT(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.add_column(
        "orders", sa.Column("payment_intent_id", sa.String(length=255), nullable=True)
    )
    op.add_column("orders", sa.Column("total_price", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "total_price")
    op.drop_column("orders", "payment_intent_id")
    op.alter_column(
        "order_items",
        "price_at_purchase",
        existing_type=sa.Integer(),
        type_=mysql.FLOAT(),
        existing_nullable=False,
    )
    op.alter_column(
        "books",
        "price",
        existing_type=sa.Integer(),
        type_=mysql.FLOAT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
